version: "3.9"

services:
  auth_audit:
    image: "postgres"
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "./data/postgres:/data/postgres"

volumes:
  postgresql: